pipeline {
    agent any

    environment {
        MAVEN_HOME = tool name: 'Maven 2', type: 'maven'
        JAVA_HOME = tool name: 'JDK 17', type: 'jdk'
        GIT_HOME = tool name: 'Git', type: 'git'
    }

    stages {
        stage('Checkout') {
            steps {
                echo "Checking out the repository..."
                git branch: 'master', url: 'https://github.com/gszybiak/km-to-mile-converter.git'
            }
        }

        stage('Build & Test') {
            steps {
                echo "Building and testing..."
                bat "mvn clean install -f ${env.WORKSPACE}/km-to-mile-converter/pom.xml"
            }
        }

        stage('Deploy') {
            steps {
                echo "Deploying the application..."
                bat "mvn spring-boot:run -f ${env.WORKSPACE}/km-to-mile-converter/pom.xml"
            }
        }
    }

    post {
        always {
            script {
                echo "Archiving test results..."
            }
            junit '**/target/surefire-reports/*.xml'
        }
    }
}