pipeline {
    agent any

    environment {
        MAVEN_HOME = tool name: 'Maven 2', type: 'maven'
        JAVA_HOME = tool name: 'JDK 17', type: 'jdk'
        GIT_HOME = tool name: 'Git', type: 'git'
        PATH = "${env.PATH};${MAVEN_HOME}\\bin;${JAVA_HOME}\\bin;${GIT_HOME}\\bin;C:\\Windows\\System32;C:\\Program Files\\Git\\cmd"
    }

    stages {
        stage('Checkout') {
            steps {
                script {
                    echo "Checking out the repository..."
                    git branch: 'master', url: 'https://github.com/gszybiak/km-to-mile-converter.git'
                }
            }
        }

        stage('Debug CMD') {
            steps {
                script {
                    echo "PATH: ${env.PATH}"
                    bat "echo Hello World"
                    bat "cmd /c echo CMD is working"
                }
            }
        }

        stage('Build & Test') {
            steps {
                script {
                    echo "MAVEN_HOME: ${MAVEN_HOME}"
                    echo "JAVA_HOME: ${JAVA_HOME}"
                    echo "GIT_HOME: ${GIT_HOME}"
                    bat "mvn.cmd -version" // Sprawdzenie wersji Maven
                    bat "mvn.cmd clean test" // Kompilacja i uruchomienie testów
                }
            }
        }

        stage('Deploy') {
            steps {
                script {
                    echo "Starting the application..."
                    bat "mvn.cmd spring-boot:run"
                }
            }
        }
    }

    post {
        always {
            script {
                echo "Archiving test results..."
            }
            junit '**/target/surefire-reports/*.xml' // Raporty testowe Surefire
        }
    }
}
