pipeline {
    agent any

    environment {
        MAVEN_HOME = tool name: 'Maven 2', type: 'maven'
        JAVA_HOME = tool name: 'JDK 17', type: 'jdk'
        PATH = "${env.PATH};${MAVEN_HOME}\\bin;${JAVA_HOME}\\bin"
    }

    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/gszybiak/km-to-mile-converter.git'
            }
        }

        stage('Build & Test') {
            steps {
                script {
                    echo "MAVEN_HOME: ${MAVEN_HOME}"
                    echo "JAVA_HOME: ${JAVA_HOME}"
                    echo "PATH: ${env.PATH}"
                    bat "mvn.cmd -version"
                    bat "mvn.cmd clean test"
                }
            }
        }

        stage('Deploy') {
            steps {
                script {
                    bat "mvn.cmd spring-boot:run"
                }
            }
        }
    }

    post {
        always {
            junit '**/target/surefire-reports/*.xml'
        }
    }
}
